/// <reference path="./webmcp.d.ts" />
import { DECK_TICKS, type DeckSoundProfile } from './deck.ts';
import { CYCLE_TICKS, MAX_MUSICAL_CYCLE, MusicController } from './music-controller.ts';
import type { CueAction, DeckId, MusicInstrument, MusicalTime, RelativeBoundary, SoloEvent } from './music-types.ts';

type JsonSchema = Record<string, unknown>;
type Issue = { path: string; code: string; message: string };
const result = (value: unknown) => ({ content: [{ type: 'text', text: JSON.stringify(value) }], structuredContent: value });
const errorResult = (code: string, message: string, issues?: Issue[]) => result({ ok: false, code, message, ...(issues?.length ? { issues } : {}) });
const objectSchema = (properties: Record<string, JsonSchema>, required: string[] = []): JsonSchema => ({ type: 'object', properties, required, additionalProperties: false });
const timeSchema: JsonSchema = objectSchema({ cycle: { type: 'integer', minimum: 0, maximum: MAX_MUSICAL_CYCLE }, bar: { type: 'integer', minimum: 0, maximum: 23 }, tick: { type: 'integer', minimum: 0, maximum: 1919 } }, ['cycle', 'bar', 'tick']);
const boundarySchema: JsonSchema = { type: 'string', enum: ['next-eighth', 'next-bar', 'next-four-bar-boundary'] };
const deckSchema: JsonSchema = { type: 'string', enum: ['A', 'B'] };
const instrumentSchema: JsonSchema = { type: 'string', enum: ['drums', 'bass', 'chords', 'lead'] };
const idSchema: JsonSchema = { type: 'string', minLength: 1, maxLength: 80 };
const profileSchema: JsonSchema = { type: 'object', properties: { presetId: { type: 'string', minLength: 1, maxLength: 128 }, controls: { type: 'object', additionalProperties: { type: 'number' } }, parameters: { type: 'object', additionalProperties: { type: 'number' } }, volume: { type: 'number', minimum: 0, maximum: 1 }, drumModel: { type: 'string', enum: ['layered', 'noisy', 'electronic'] } }, required: ['presetId', 'controls', 'parameters', 'volume'], additionalProperties: false };
const voicingSchema: JsonSchema = { type: 'string', enum: ['root', 'open', 'first-inversion', 'second-inversion', 'third-inversion'] };
const articulationSchema: JsonSchema = { type: 'number', minimum: .05, maximum: 1 };
const deckTickSchema: JsonSchema = { type: 'integer', minimum: 0, maximum: DECK_TICKS - 240, multipleOf: 240 };
const deckDurationSchema: JsonSchema = { type: 'integer', minimum: 240, maximum: DECK_TICKS, multipleOf: 240 };
const soloDurationSchema: JsonSchema = { type: 'integer', minimum: 240, maximum: CYCLE_TICKS, multipleOf: 240 };
const noteSchema: JsonSchema = objectSchema({ type: { type: 'string', enum: ['note'] }, id: idSchema, instrument: { type: 'string', enum: ['bass', 'lead'] }, startTick: deckTickSchema, durationTicks: deckDurationSchema, pitch: { type: 'integer', minimum: 0, maximum: 127 }, velocity: { type: 'number', minimum: 0, maximum: 1 }, articulation: articulationSchema }, ['type', 'instrument', 'startTick', 'durationTicks', 'pitch', 'velocity']);
const drumSchema: JsonSchema = objectSchema({ type: { type: 'string', enum: ['drum'] }, id: idSchema, startTick: deckTickSchema, pad: { type: 'integer', minimum: 0, maximum: 11 }, velocity: { type: 'number', minimum: 0, maximum: 1 } }, ['type', 'startTick', 'pad', 'velocity']);
const chordSchema: JsonSchema = objectSchema({ type: { type: 'string', enum: ['chord'] }, id: idSchema, startTick: deckTickSchema, durationTicks: deckDurationSchema, symbol: { type: 'string', minLength: 1, maxLength: 80 }, pitches: { type: 'array', minItems: 1, maxItems: 8, items: { type: 'integer', minimum: 0, maximum: 127 } }, velocity: { type: 'number', minimum: 0, maximum: 1 }, voicing: voicingSchema, articulation: articulationSchema }, ['type', 'startTick', 'durationTicks', 'symbol', 'pitches']);
const deckEventSchema: JsonSchema = { oneOf: [drumSchema, noteSchema, chordSchema] };
const soloDrumSchema: JsonSchema = objectSchema({ type: { type: 'string', enum: ['drum'] }, id: idSchema, start: timeSchema, pad: { type: 'integer', minimum: 0, maximum: 11 }, velocity: { type: 'number', minimum: 0, maximum: 1 } }, ['type', 'start', 'pad', 'velocity']);
const soloNoteSchema: JsonSchema = objectSchema({ type: { type: 'string', enum: ['note'] }, id: idSchema, start: timeSchema, instrument: { type: 'string', enum: ['bass', 'lead'] }, durationTicks: soloDurationSchema, pitch: { type: 'integer', minimum: 0, maximum: 127 }, velocity: { type: 'number', minimum: 0, maximum: 1 }, articulation: articulationSchema }, ['type', 'start', 'instrument', 'durationTicks', 'pitch', 'velocity']);
const soloChordSchema: JsonSchema = objectSchema({ type: { type: 'string', enum: ['chord'] }, id: idSchema, start: timeSchema, durationTicks: soloDurationSchema, symbol: { type: 'string', minLength: 1, maxLength: 80 }, pitches: { type: 'array', minItems: 1, maxItems: 8, items: { type: 'integer', minimum: 0, maximum: 127 } }, velocity: { type: 'number', minimum: 0, maximum: 1 }, voicing: voicingSchema, articulation: articulationSchema }, ['type', 'start', 'durationTicks', 'symbol', 'pitches']);
const soloEventSchema: JsonSchema = { oneOf: [soloDrumSchema, soloNoteSchema, soloChordSchema] };
const strict = (input: unknown, required: string[], optional: string[] = []) => { if (!isRecord(input) || !required.every((key) => key in input)) return null; const allowed = new Set([...required, ...optional]); return Object.keys(input).every((key) => allowed.has(key)) ? input : null; };
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === 'object' && !Array.isArray(value);
const isNumber = (value: unknown, min: number, max: number) => typeof value === 'number' && Number.isFinite(value) && value >= min && value <= max;
const isTime = (value: unknown): value is MusicalTime => isRecord(value) && Object.keys(value).length === 3 && Number.isInteger(value.cycle) && isNumber(value.cycle, 0, MAX_MUSICAL_CYCLE) && Number.isInteger(value.bar) && isNumber(value.bar, 0, 23) && Number.isInteger(value.tick) && isNumber(value.tick, 0, 1919);
const stringId = (value: unknown, max = 80) => typeof value === 'string' && value.length > 0 && value.length <= max;
const isDeck = (value: unknown): value is DeckId => value === 'A' || value === 'B';
const isInstrument = (value: unknown): value is MusicInstrument => value === 'drums' || value === 'bass' || value === 'chords' || value === 'lead';
const isLane = (value: unknown): value is 'live' | 'deckA' | 'deckB' | 'solo' => value === 'live' || value === 'deckA' || value === 'deckB' || value === 'solo';
const isProfileSource = (value: unknown): value is 'live' | 'deckA' | 'deckB' | 'activeSolo' => value === 'live' || value === 'deckA' || value === 'deckB' || value === 'activeSolo';
const isWaveform = (value: unknown): value is OscillatorType => value === 'sine' || value === 'triangle' || value === 'square' || value === 'sawtooth';
const isProfile = (value: unknown): value is DeckSoundProfile => isRecord(value) && stringId(value.presetId, 128) && isRecord(value.controls) && isRecord(value.parameters) && Object.values(value.controls).every((item) => typeof item === 'number' && Number.isFinite(item)) && Object.values(value.parameters).every((item) => typeof item === 'number' && Number.isFinite(item)) && isNumber(value.volume, 0, 1) && (value.drumModel === undefined || value.drumModel === 'layered' || value.drumModel === 'noisy' || value.drumModel === 'electronic');
const timingSchema = (properties: Record<string, JsonSchema>, required: string[]): JsonSchema => { const schemaRequired = required.filter((name) => name !== 'transitionTicks'); return { oneOf: [objectSchema({ at: timeSchema, ...properties }, ['at', ...schemaRequired]), objectSchema({ when: boundarySchema, ...properties }, ['when', ...schemaRequired])], additionalProperties: false }; };
const normalAnnotations = { readOnlyHint: false, destructiveHint: false, untrustedContentHint: false };
const readAnnotations = { readOnlyHint: true, destructiveHint: false, untrustedContentHint: false };
const parseTiming = (input: Record<string, unknown>) => {
  const hasAt = 'at' in input;
  const hasWhen = 'when' in input;
  if (hasAt && !isTime(input.at)) return { issues: [{ path: 'at', code: 'INVALID', message: 'at must be a safe MusicalTime.' }] };
  if (hasWhen && input.when !== 'next-eighth' && input.when !== 'next-bar' && input.when !== 'next-four-bar-boundary') return { issues: [{ path: 'when', code: 'ENUM', message: 'when must be a supported relative boundary.' }] };
  if (hasAt === hasWhen) return { issues: [{ path: 'timing', code: 'ONE_OF', message: 'Provide exactly one of at or when.' }] };
  return { timing: hasAt ? { at: input.at as MusicalTime } : { when: input.when as RelativeBoundary } };
};

export const buildWebMcpTools = (music: MusicController): WebMcpTool[] => {
  const cueTool = (name: string, title: string, description: string, schema: JsonSchema, required: string[], optional: string[], makeAction: (input: Record<string, unknown>) => CueAction | null): WebMcpTool => ({ name, title, description, inputSchema: schema, annotations: normalAnnotations, execute: (raw) => { const runtimeRequired = name === 'music_cue_set_deck_sound_profile' ? required.filter((field) => field !== 'transitionTicks') : required; const runtimeOptional = name === 'music_cue_set_deck_sound_profile' ? [...optional, 'transitionTicks'] : optional; const input = strict(raw, runtimeRequired, [...runtimeOptional, 'at', 'when']); if (!input) return errorResult('INVALID_INPUT', 'Cue fields are invalid or contain unknown fields.'); const parsed = parseTiming(input); if (!('timing' in parsed)) return errorResult('INVALID_TIMING', 'The timing form is invalid.', parsed.issues); const action = makeAction(input); return action ? result(music.queueAction(parsed.timing!, action)) : errorResult('INVALID_INPUT', 'The cue fields do not match the action.'); } });
  const debugTool = (name: string, title: string, description: string, schema: JsonSchema, required: string[], optional: string[], execute: (input: Record<string, unknown>) => unknown | Promise<unknown>): WebMcpTool => ({ name, title, description, inputSchema: schema, annotations: normalAnnotations, execute: (raw) => { const input = strict(raw, required, optional); return input ? execute(input) : errorResult('INVALID_INPUT', 'Debug fields are invalid or contain unknown fields.'); } });
  const heldRetriggerSchema = objectSchema({ firstId: idSchema, firstFrequencyHz: { type: 'number', minimum: 20, maximum: 5000 }, secondId: idSchema, secondFrequencyHz: { type: 'number', minimum: 20, maximum: 5000 }, firstHoldMs: { type: 'number', minimum: 10, maximum: 10000 }, retriggerGapMs: { type: 'number', minimum: -100, maximum: 100 }, secondHoldMs: { type: 'number', minimum: 10, maximum: 10000 }, bandIndices: { type: 'array', maxItems: 128, items: { type: 'integer', minimum: 0, maximum: 127 } }, minFrequencyHz: { type: 'number', minimum: 20, maximum: 20000 }, maxFrequencyHz: { type: 'number', minimum: 20, maximum: 20000 }, captureLeadMs: { type: 'number', minimum: 0, maximum: 1000 }, captureTailMs: { type: 'number', minimum: 0, maximum: 2000 }, maxSamples: { type: 'integer', minimum: 1, maximum: 600 } });
  const heldRetriggerRequired = ['firstId', 'firstFrequencyHz', 'secondId', 'secondFrequencyHz', 'firstHoldMs', 'retriggerGapMs', 'secondHoldMs'];
  const heldRetriggerInputSchema = { ...heldRetriggerSchema, required: heldRetriggerRequired };
  const runHeldRetrigger = (input: Record<string, unknown>) => {
    const issue = (path: string, message: string) => errorResult('INVALID_INPUT', message, [{ path, code: 'INVALID', message }]);
    if (!stringId(input.firstId)) return issue('firstId', 'firstId must be a nonempty bounded string.');
    if (!isNumber(input.firstFrequencyHz, 20, 5000)) return issue('firstFrequencyHz', 'firstFrequencyHz must be between 20 and 5000 Hz.');
    if (!stringId(input.secondId)) return issue('secondId', 'secondId must be a nonempty bounded string.');
    if (input.firstId === input.secondId) return issue('secondId', 'secondId must differ from firstId.');
    if (!isNumber(input.secondFrequencyHz, 20, 5000)) return issue('secondFrequencyHz', 'secondFrequencyHz must be between 20 and 5000 Hz.');
    if (!isNumber(input.firstHoldMs, 10, 10000)) return issue('firstHoldMs', 'firstHoldMs must be between 10 and 10000 ms.');
    if (!isNumber(input.retriggerGapMs, -100, 100)) return issue('retriggerGapMs', 'retriggerGapMs must be between -100 and 100 ms.');
    if (!isNumber(input.secondHoldMs, 10, 10000)) return issue('secondHoldMs', 'secondHoldMs must be between 10 and 10000 ms.');
    if ((input.retriggerGapMs as number) < 0 && (input.firstHoldMs as number) < Math.abs(input.retriggerGapMs as number)) return issue('retriggerGapMs', 'Negative overlap cannot begin before the first hold.');
    if (input.bandIndices !== undefined && (!Array.isArray(input.bandIndices) || input.bandIndices.length > 128 || input.bandIndices.some((value) => !Number.isInteger(value) || !isNumber(value, 0, 127)))) return issue('bandIndices', 'bandIndices must contain at most 128 integers from 0 to 127.');
    if (input.minFrequencyHz !== undefined && !isNumber(input.minFrequencyHz, 20, 20000)) return issue('minFrequencyHz', 'Minimum frequency is invalid.');
    if (input.maxFrequencyHz !== undefined && !isNumber(input.maxFrequencyHz, 20, 20000)) return issue('maxFrequencyHz', 'Maximum frequency is invalid.');
    if (input.minFrequencyHz !== undefined && input.maxFrequencyHz !== undefined && (input.minFrequencyHz as number) >= (input.maxFrequencyHz as number)) return issue('frequencyRange', 'Minimum frequency must be below maximum frequency.');
    if (input.captureLeadMs !== undefined && !isNumber(input.captureLeadMs, 0, 1000)) return issue('captureLeadMs', 'Capture lead is invalid.');
    if (input.captureTailMs !== undefined && !isNumber(input.captureTailMs, 0, 2000)) return issue('captureTailMs', 'Capture tail is invalid.');
    if (input.maxSamples !== undefined && (!Number.isInteger(input.maxSamples) || !isNumber(input.maxSamples, 1, 600))) return issue('maxSamples', 'maxSamples must be an integer from 1 to 600.');
    return result(music.debugRunHeldRetriggerProbe(input as never));
  };
  const tools: WebMcpTool[] = [
    { name: 'music_get_state', title: 'Get music state', description: 'Read-only. Returns both decks, shared clock, profiles, enabled instruments, transfer, solo, cues, chord context, and bounded human live performance state.', inputSchema: objectSchema({ includeParameters: { type: 'boolean', default: false }, includeExecutedCues: { type: 'boolean', default: false }, includeLiveEvents: { type: 'boolean', default: true }, liveSinceSequence: { type: 'integer', minimum: 0 }, maxLiveEvents: { type: 'integer', minimum: 0, maximum: 256, default: 64 } }), annotations: readAnnotations, execute: (raw) => { const input = raw === undefined ? {} : strict(raw, [], ['includeParameters', 'includeExecutedCues', 'includeLiveEvents', 'liveSinceSequence', 'maxLiveEvents']); if (!input || (input.includeParameters !== undefined && typeof input.includeParameters !== 'boolean') || (input.includeExecutedCues !== undefined && typeof input.includeExecutedCues !== 'boolean') || (input.includeLiveEvents !== undefined && typeof input.includeLiveEvents !== 'boolean') || (input.liveSinceSequence !== undefined && (!Number.isInteger(input.liveSinceSequence) || !isNumber(input.liveSinceSequence, 0, Number.MAX_SAFE_INTEGER))) || (input.maxLiveEvents !== undefined && (!Number.isInteger(input.maxLiveEvents) || !isNumber(input.maxLiveEvents, 0, 256)))) return errorResult('INVALID_INPUT', 'State options are invalid.'); return result({ ok: true, code: 'STATE', message: 'Current music state.', data: music.getState({ includeParameters: input.includeParameters === true, includeExecutedCues: input.includeExecutedCues === true, includeLiveEvents: input.includeLiveEvents !== false, liveSinceSequence: input.liveSinceSequence as number | undefined, maxLiveEvents: input.maxLiveEvents as number | undefined }) }); } },
    { name: 'music_get_earliest_safe_time', title: 'Get earliest safe cue time', description: 'Read-only. Returns the earliest future AudioContext and MusicalTime boundary for a cue.', inputSchema: objectSchema({}), annotations: readAnnotations, execute: (raw) => strict(raw === undefined ? {} : raw, []) ? result(music.getEarliestSafeTime()) : errorResult('INVALID_INPUT', 'No input fields are accepted.') },
    { name: 'music_start_transport', title: 'Start music transport', description: 'Acts immediately. Starts or resumes the shared transport after audio exists.', inputSchema: objectSchema({}), annotations: normalAnnotations, execute: async (raw) => strict(raw === undefined ? {} : raw, []) ? result(await music.startTransport()) : errorResult('INVALID_INPUT', 'No input fields are accepted.') },
    { name: 'music_stop_transport', title: 'Stop music transport', description: 'Acts immediately. Freezes global time, silences deck lanes, and requeues scheduled cues.', inputSchema: objectSchema({}), annotations: normalAnnotations, execute: (raw) => strict(raw === undefined ? {} : raw, []) ? result(music.stopTransport()) : errorResult('INVALID_INPUT', 'No input fields are accepted.') },
    cueTool('music_cue_add_deck_events', 'Cue deck events', 'Queues quantised deck events; it does not commit them immediately.', timingSchema({ deck: deckSchema, instrument: instrumentSchema, events: { type: 'array', minItems: 1, maxItems: 256, items: deckEventSchema } }, ['deck', 'instrument', 'events']), ['deck', 'instrument', 'events'], [], (input) => isDeck(input.deck) && isInstrument(input.instrument) && Array.isArray(input.events) ? { type: 'add-deck-events', deck: input.deck, instrument: input.instrument, events: input.events as never[] } : null),
    cueTool('music_cue_remove_deck_events', 'Cue deck event removal', 'Queues removal of committed deck events; it does not remove them immediately.', timingSchema({ deck: deckSchema, instrument: instrumentSchema, eventIds: { type: 'array', minItems: 1, maxItems: 256, items: idSchema } }, ['deck', 'instrument', 'eventIds']), ['deck', 'instrument', 'eventIds'], [], (input) => isDeck(input.deck) && isInstrument(input.instrument) && Array.isArray(input.eventIds) ? { type: 'remove-deck-events', deck: input.deck, instrument: input.instrument, eventIds: input.eventIds as string[] } : null),
    cueTool('music_cue_replace_deck_events', 'Cue deck range replacement', 'Queues atomic replacement inside a local eighth-note deck range.', timingSchema({ deck: deckSchema, instrument: instrumentSchema, fromTick: { type: 'integer', minimum: 0, maximum: DECK_TICKS }, toTick: { type: 'integer', minimum: 0, maximum: DECK_TICKS }, events: { type: 'array', minItems: 1, maxItems: 256, items: deckEventSchema } }, ['deck', 'instrument', 'fromTick', 'toTick', 'events']), ['deck', 'instrument', 'fromTick', 'toTick', 'events'], [], (input) => isDeck(input.deck) && isInstrument(input.instrument) && Array.isArray(input.events) ? { type: 'replace-deck-events', deck: input.deck, instrument: input.instrument, fromTick: input.fromTick as number, toTick: input.toTick as number, events: input.events as never[] } : null),
    cueTool('music_cue_set_instrument_enabled', 'Cue global instrument state', 'Queues a global instrument enable change at the boundary.', timingSchema({ instrument: instrumentSchema, enabled: { type: 'boolean' } }, ['instrument', 'enabled']), ['instrument', 'enabled'], [], (input) => isInstrument(input.instrument) && typeof input.enabled === 'boolean' ? { type: 'set-instrument-enabled', instrument: input.instrument, enabled: input.enabled } : null),
    cueTool('music_cue_set_deck_sound_profile', 'Cue deck sound profile', 'Queues a complete deck profile change at the boundary.', timingSchema({ deck: deckSchema, instrument: instrumentSchema, profile: profileSchema, transitionTicks: { type: 'integer', minimum: 0, maximum: DECK_TICKS } }, ['deck', 'instrument', 'profile', 'transitionTicks']), ['deck', 'instrument', 'profile', 'transitionTicks'], [], (input) => isDeck(input.deck) && isInstrument(input.instrument) && isProfile(input.profile) ? { type: 'set-deck-sound-profile', deck: input.deck, instrument: input.instrument, profile: input.profile, transitionTicks: input.transitionTicks as number | undefined } : null),
    cueTool('music_cue_transfer', 'Cue deck transfer', 'Queues a cut, crossfade, dip, or overlap between Deck A and Deck B.', timingSchema({ destination: deckSchema, style: { type: 'string', enum: ['cut', 'blend', 'dip', 'overlap'] }, durationTicks: { type: 'integer', minimum: 0, maximum: CYCLE_TICKS } }, ['destination', 'style', 'durationTicks']), ['destination', 'style', 'durationTicks'], [], (input) => isDeck(input.destination) && (input.style === 'cut' || input.style === 'blend' || input.style === 'dip' || input.style === 'overlap') ? { type: 'transfer-deck', destination: input.destination, style: input.style, durationTicks: input.durationTicks as number } : null),
    cueTool('music_cue_start_solo', 'Cue solo start', 'Queues an empty solo buffer.', timingSchema({ soloId: idSchema, instrument: instrumentSchema, description: { type: 'string', minLength: 1, maxLength: 240 }, lengthBars: { type: 'integer', minimum: 1, maximum: 24 }, soundProfile: profileSchema }, ['soloId', 'instrument', 'description', 'lengthBars', 'soundProfile']), ['soloId', 'instrument', 'description', 'lengthBars', 'soundProfile'], [], (input) => stringId(input.soloId) && isInstrument(input.instrument) && typeof input.description === 'string' && Number.isInteger(input.lengthBars) && isNumber(input.lengthBars, 1, 24) && isProfile(input.soundProfile) ? { type: 'start-solo', soloId: input.soloId as string, instrument: input.instrument, description: input.description, lengthBars: input.lengthBars as number, soundProfile: input.soundProfile } : null),
    cueTool('music_cue_create_solo', 'Cue atomic solo', 'Queues creation of one solo and its complete event buffer as one action.', timingSchema({ soloId: idSchema, instrument: instrumentSchema, description: { type: 'string', minLength: 1, maxLength: 240 }, lengthBars: { type: 'integer', minimum: 1, maximum: 24 }, soundProfile: profileSchema, events: { type: 'array', minItems: 1, maxItems: 256, items: soloEventSchema } }, ['soloId', 'instrument', 'description', 'lengthBars', 'soundProfile', 'events']), ['soloId', 'instrument', 'description', 'lengthBars', 'soundProfile', 'events'], [], (input) => stringId(input.soloId) && isInstrument(input.instrument) && typeof input.description === 'string' && Number.isInteger(input.lengthBars) && isNumber(input.lengthBars, 1, 24) && isProfile(input.soundProfile) && Array.isArray(input.events) ? { type: 'create-solo', soloId: input.soloId as string, instrument: input.instrument, description: input.description, lengthBars: input.lengthBars as number, soundProfile: input.soundProfile, events: input.events as SoloEvent[] } : null),
    cueTool('music_cue_add_solo_events', 'Cue solo events', 'Queues globally timed events into an existing solo.', timingSchema({ soloId: idSchema, events: { type: 'array', minItems: 1, maxItems: 256, items: soloEventSchema } }, ['soloId', 'events']), ['soloId', 'events'], [], (input) => stringId(input.soloId) && Array.isArray(input.events) ? { type: 'add-solo-events', soloId: input.soloId as string, events: input.events as SoloEvent[] } : null),
    cueTool('music_cue_end_solo_early', 'Cue solo end', 'Queues an exceptional early solo end.', timingSchema({ soloId: idSchema }, ['soloId']), ['soloId'], [], (input) => stringId(input.soloId) ? { type: 'end-solo-early', soloId: input.soloId as string } : null),
    { name: 'music_cancel_cue', title: 'Cancel music cue', description: 'Cancels only a pending or scheduled cue.', inputSchema: objectSchema({ cueId: idSchema }, ['cueId']), annotations: normalAnnotations, execute: (raw) => { const input = strict(raw, ['cueId']); return input && stringId(input.cueId) ? result(music.cancelCue(input.cueId as string)) : errorResult('INVALID_INPUT', 'cueId must be a nonempty bounded string.'); } },
    { name: 'music_undo_last_agent_action', title: 'Undo agent action', description: 'Undoes the latest agent action with target-scoped conflict checks.', inputSchema: objectSchema({}), annotations: normalAnnotations, execute: (raw) => strict(raw === undefined ? {} : raw, []) ? result(music.undoLastAgentAction()) : errorResult('INVALID_INPUT', 'No input fields are accepted.') },
    debugTool('debug_start_audio', 'Temporary start audio', 'Temporary immediate action. Starts or resumes AudioContext without starting transport.', objectSchema({}), [], [], async () => music.debugStartAudio()),
    debugTool('debug_hold_instrument_frequency', 'Temporary hold frequency', 'Temporary immediate action. Holds a real bass or lead note until release.', objectSchema({ id: idSchema, instrument: { type: 'string', enum: ['bass', 'lead'] }, frequencyHz: { type: 'number', minimum: 20, maximum: 5000 } }, ['id', 'instrument', 'frequencyHz']), ['id', 'instrument', 'frequencyHz'], [], (input) => result(music.debugHoldInstrumentFrequency({ id: input.id as string, instrument: input.instrument as 'bass' | 'lead', frequencyHz: input.frequencyHz as number }))),
    { name: 'debug_release_held_note', title: 'Temporary release held note', description: 'Temporary immediate action. Releases one held debug note.', inputSchema: objectSchema({ id: idSchema }, ['id']), annotations: normalAnnotations, execute: (raw) => { const input = strict(raw, ['id']); return input && stringId(input.id) ? result(music.debugReleaseHeldNote(input.id as string)) : errorResult('INVALID_INPUT', 'id must be a bounded string.'); } },
    debugTool('debug_play_tone', 'Temporary debug tone', 'Temporary immediate diagnostic oscillator.', objectSchema({ frequencyHz: { type: 'number', minimum: 20, maximum: 20000 }, durationMs: { type: 'number', minimum: 10, maximum: 10000 }, waveform: { type: 'string', enum: ['sine', 'triangle', 'square', 'sawtooth'] }, gain: { type: 'number', minimum: 0, maximum: .25 }, attackMs: { type: 'number', minimum: 1, maximum: 100 }, releaseMs: { type: 'number', minimum: 5, maximum: 2000 }, delayMs: { type: 'number', minimum: 0, maximum: 5000 } }, ['frequencyHz', 'durationMs']), ['frequencyHz', 'durationMs'], ['waveform', 'gain', 'attackMs', 'releaseMs', 'delayMs'], (input) => isNumber(input.frequencyHz, 20, 20000) && isNumber(input.durationMs, 10, 10000) && (input.waveform === undefined || isWaveform(input.waveform)) && (input.gain === undefined || isNumber(input.gain, 0, .25)) && (input.attackMs === undefined || isNumber(input.attackMs, 1, 100)) && (input.releaseMs === undefined || isNumber(input.releaseMs, 5, 2000)) && (input.delayMs === undefined || isNumber(input.delayMs, 0, 5000)) ? result(music.debugPlayTone(input as never)) : errorResult('INVALID_INPUT', 'Debug tone values are invalid.')),
    debugTool('debug_play_instrument_frequency', 'Temporary instrument frequency', 'Temporary immediate action. Exercises bass or lead at an exact frequency.', objectSchema({ instrument: { type: 'string', enum: ['bass', 'lead'] }, frequencyHz: { type: 'number', minimum: 20, maximum: 5000 }, durationMs: { type: 'number', minimum: 10, maximum: 10000 }, velocity: { type: 'number', minimum: 0, maximum: 1 }, lane: { type: 'string', enum: ['live', 'deckA', 'deckB', 'solo'] }, profileSource: { type: 'string', enum: ['live', 'deckA', 'deckB', 'activeSolo'] } }, ['instrument', 'frequencyHz', 'durationMs']), ['instrument', 'frequencyHz', 'durationMs'], ['velocity', 'lane', 'profileSource'], (input) => (input.instrument === 'bass' || input.instrument === 'lead') && isNumber(input.frequencyHz, 20, 5000) && isNumber(input.durationMs, 10, 10000) && (input.velocity === undefined || isNumber(input.velocity, 0, 1)) && (input.lane === undefined || isLane(input.lane)) && (input.profileSource === undefined || isProfileSource(input.profileSource)) ? result(music.debugPlayInstrumentFrequency(input as never)) : errorResult('INVALID_INPUT', 'Debug instrument values are invalid.')),
    debugTool('debug_play_drum', 'Temporary drum hit', 'Temporary immediate procedural drum action.', objectSchema({ pad: { type: 'integer', minimum: 0, maximum: 11 }, velocity: { type: 'number', minimum: 0, maximum: 1 }, lane: { type: 'string', enum: ['live', 'deckA', 'deckB', 'solo'] }, profileSource: { type: 'string', enum: ['live', 'deckA', 'deckB', 'activeSolo'] }, delayMs: { type: 'number', minimum: 0, maximum: 5000 } }, ['pad']), ['pad'], ['velocity', 'lane', 'profileSource', 'delayMs'], (input) => Number.isInteger(input.pad) && isNumber(input.pad, 0, 11) && (input.velocity === undefined || isNumber(input.velocity, 0, 1)) && (input.lane === undefined || isLane(input.lane)) && (input.profileSource === undefined || isProfileSource(input.profileSource)) && (input.delayMs === undefined || isNumber(input.delayMs, 0, 5000)) ? result(music.debugPlayDrum(input as never)) : errorResult('INVALID_INPUT', 'Debug drum values are invalid.')),
    { name: 'debug_stop_all', title: 'Temporary stop voices', description: 'Temporary immediate action. Stops debug voices, or all sounding voices when scope is all.', inputSchema: objectSchema({ scope: { type: 'string', enum: ['debug', 'all'] } }), annotations: { readOnlyHint: false, destructiveHint: true, untrustedContentHint: false }, execute: (raw) => { const input = strict(raw === undefined ? {} : raw, [], ['scope']); return input && (input.scope === undefined || input.scope === 'debug' || input.scope === 'all') ? result(music.debugStopAll(input.scope as 'debug' | 'all' | undefined)) : errorResult('INVALID_INPUT', 'scope must be debug or all.'); } },
    { name: 'debug_get_frequency_histogram', title: 'Read frequency histogram', description: 'Read-only. Returns chronological FFT history with explicit decimation or band selection.', inputSchema: objectSchema({ seconds: { type: 'number', minimum: .25, maximum: 10 }, includeIntensities: { type: 'boolean' }, maxSamples: { type: 'integer', minimum: 1, maximum: 600 }, bands: { type: 'array', maxItems: 128, items: { type: 'integer', minimum: 0, maximum: 127 } }, summaryOnly: { type: 'boolean' } }), annotations: readAnnotations, execute: (raw) => { const input = strict(raw === undefined ? {} : raw, [], ['seconds', 'includeIntensities', 'maxSamples', 'bands', 'summaryOnly']); if (!input || (input.seconds !== undefined && !isNumber(input.seconds, .25, 10)) || (input.includeIntensities !== undefined && typeof input.includeIntensities !== 'boolean') || (input.maxSamples !== undefined && (!Number.isInteger(input.maxSamples) || !isNumber(input.maxSamples, 1, 600))) || (input.bands !== undefined && (!Array.isArray(input.bands) || input.bands.length > 128 || input.bands.some((band) => !Number.isInteger(band) || !isNumber(band, 0, 127)))) || (input.summaryOnly !== undefined && typeof input.summaryOnly !== 'boolean')) return errorResult('INVALID_INPUT', 'Histogram options are invalid.'); return result({ ok: true, code: 'HISTOGRAM', message: 'Current frequency histogram.', data: music.histogram.snapshot(input.seconds as number | undefined, input.includeIntensities === true, { maxSamples: input.maxSamples as number | undefined, bandIndices: input.bands as number[] | undefined, summaryOnly: input.summaryOnly === true }) }); } },
    { name: 'debug_clear_frequency_histogram', title: 'Clear frequency histogram', description: 'Temporary immediate action. Clears only histogram history.', inputSchema: objectSchema({}), annotations: normalAnnotations, execute: (raw) => strict(raw === undefined ? {} : raw, []) ? result(music.debugClearHistogram()) : errorResult('INVALID_INPUT', 'No input fields are accepted.') },
    { name: 'debug_export_snapshot', title: 'Read debug snapshot', description: 'Read-only. Returns the same complete snapshot used by Export JSON.', inputSchema: objectSchema({}), annotations: readAnnotations, execute: (raw) => strict(raw === undefined ? {} : raw, []) ? result(music.debugExportSnapshot()) : errorResult('INVALID_INPUT', 'No input fields are accepted.') },
    debugTool('debug_run_release_probe', 'Temporary release probe', 'Temporary immediate action. Schedules a deterministic bass or lead release run.', objectSchema({ instrument: { type: 'string', enum: ['bass', 'lead'] }, frequencyHz: { type: 'number', minimum: 20, maximum: 5000 }, holdMs: { type: 'number', minimum: 10, maximum: 10000 }, releaseMs: { type: 'number', minimum: 5, maximum: 2000 }, velocity: { type: 'number', minimum: 0, maximum: 1 }, repetitions: { type: 'integer', minimum: 1, maximum: 16 }, gapMs: { type: 'number', minimum: 50, maximum: 2000 } }), ['instrument', 'frequencyHz', 'holdMs', 'releaseMs', 'velocity', 'repetitions', 'gapMs'], [], (input) => (input.instrument === 'bass' || input.instrument === 'lead') && isNumber(input.frequencyHz, 20, 5000) && isNumber(input.holdMs, 10, 10000) && isNumber(input.releaseMs, 5, 2000) && isNumber(input.velocity, 0, 1) && Number.isInteger(input.repetitions) && isNumber(input.repetitions, 1, 16) && isNumber(input.gapMs, 50, 2000) ? result(music.debugRunReleaseProbe(input as never)) : errorResult('INVALID_INPUT', 'Release probe values are invalid.')),
    { name: 'debug_get_release_probe', title: 'Read release probe', description: 'Read-only. Returns release probe metadata.', inputSchema: objectSchema({ probeId: idSchema }, ['probeId']), annotations: readAnnotations, execute: (raw) => { const input = strict(raw, ['probeId']); return input && stringId(input.probeId) ? result(music.debugGetReleaseProbe(input.probeId as string)) : errorResult('INVALID_INPUT', 'probeId must be a bounded string.'); } },
    { name: 'debug_get_held_retrigger_probe', title: 'Read live retrigger probe', description: 'Read-only. Returns operation drift, diagnostics, histogram data, and a 5-8 kHz summary.', inputSchema: objectSchema({ probeId: idSchema }, ['probeId']), annotations: readAnnotations, execute: (raw) => { const input = strict(raw, ['probeId']); return input && stringId(input.probeId) ? result(music.debugGetHeldRetriggerProbe(input.probeId as string)) : errorResult('INVALID_INPUT', 'probeId must be a bounded string.'); } },
    debugTool('debug_run_held_retrigger_probe', 'Temporary live retrigger probe', 'Temporary immediate action. Runs a short-gap sequence through true live bass hold/release behavior.', heldRetriggerInputSchema, heldRetriggerRequired, ['bandIndices', 'minFrequencyHz', 'maxFrequencyHz', 'captureLeadMs', 'captureTailMs', 'maxSamples'], runHeldRetrigger),
  ];
  return tools;
};

export async function registerWebMcp(music: MusicController): Promise<() => void> {
  if (typeof document === 'undefined' || !document.modelContext) { if (import.meta.env?.DEV) console.warn('WebMCP is unavailable; synth remains usable.'); return () => {}; }
  const abort = new AbortController(); let warned = false;
  for (const tool of buildWebMcpTools(music)) { try { await document.modelContext.registerTool(tool, { signal: abort.signal }); } catch (error) { if (!warned && import.meta.env?.DEV) { warned = true; console.warn('WebMCP registration unavailable; synth remains usable.', error); } } }
  return () => abort.abort();
}
